Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., dev, staging, production)
    AllowedValues:
      - dev
      - staging
      - prod

  BucketName:
    Type: String
    Description: Name of the S3 bucket to create

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: !Ref BucketName

Outputs:
  S3Bucket:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket